### ISSUE TITLE
下载发生NullPointer错误

### ISSUE THREAD

**Issue by Link-KS** [dipoo/egdownloader#13]
不知道是不是我这边的问题。无论下载什么，都会提示NullPointerException。即使暂停下载控制台的错误信息也会每隔十秒刷新一次。控制台信息如下：
![default](https://user-images.githubusercontent.com/7877965/37568254-90f69c64-2b0d-11e8-88b9-a047791f96dd.png)

error.log 内的信息如下：

> java.lang.RuntimeException: java.lang.NullPointerException
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
> 	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(Unknown Source)
> 	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
> 	at org.arong.egdownloader.spider.WebClient.getStreamUseJavaWithCookie(WebClient.java:379)
> 	at org.arong.egdownloader.spider.WebClient.getStreamUseJava(WebClient.java:309)
> 	at org.arong.egdownloader.ui.work.DownloadWorker.doInBackground(DownloadWorker.java:79)
> 	at org.arong.egdownloader.ui.work.DownloadWorker.doInBackground(DownloadWorker.java:1)
> 	at javax.swing.SwingWorker$1.call(Unknown Source)
> 	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at javax.swing.SwingWorker.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.NullPointerException
> 	at sun.net.www.ParseUtil.toURI(Unknown Source)
> 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
> 	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
> 	... 12 more
（上述错误信息在log中重复若干遍）

**Comment by dipoo** [comment]
我的账号被谁改了浏览模式，已经改回来了，重试~

**Comment by Link-KS** [comment]
哇这么快就回复了。可是问题还没有解决呀，错误信息也还是一样……

**Comment by dipoo** [comment]
试下其他本子可不可以？或者删了重建试试？

**Comment by Link-KS** [comment]
谢谢！删了重建之后确实可以了。不过删除的时候花了很长时间。
另外其他与上面出错那个本子同时建立的任务也仍然会出错。我猜可能是因为我建立任务之后没有马上开始下载，下载之前重启了程序的缘故。会不会是你把一些什么信息写在了内存里，关闭程序就会清空，因而导致问题的发生呢？我也不是很懂编程啦，希望能帮到你

**Comment by dipoo** [comment]
no，原因是那些本子创建任务时解析出来的地址都是错的。刚才我改了浏览模式，之后创建的就能正确下载。

**Comment by dipoo** [comment]
被人改了模式而导致失败代码里已经解决，只是还没有更新到网盘，有时间吧~

**Comment by Link-KS** [comment]
再次感谢~
