### ISSUE TITLE
能否自动将文件夹自动以日文命名

### ISSUE THREAD

**Issue by li0817** [dipoo/egdownloader#15]
![image](https://user-images.githubusercontent.com/27659768/46902186-5730f080-cef3-11e8-83ba-27eadf1b5207.png)
右键详细信息后第二行有个“子XX“，想将其作为文件夹名；在配置中有个”以真实名称...“(后面看不到，窗口也拉不大)，不知道是不是这个选项，但好像勾不勾上效果都一样，都是以”详细信息“中第一行所示来命名的

不过在下载器里面倒是都以日文显示

**Comment by dipoo** [comment]
目前不行，后续可以添加进配置

**Comment by li0817** [comment]
OK，知道了；
一直在用，但最近发现文件名过长在列表视图下看不到后半部分名字，会导致想把一个系列按顺序排的时候，看不到文件夹名后面的差异，因为前半部分的名字是同个系列文字都是一样的，而换成日文后，文件夹名短了很多就很方便，故有此问_(:з」∠)_
