### ISSUE TITLE
搜索里的这些分类似乎没有用，

### ISSUE THREAD

**Issue by moyuxia** [dipoo/egdownloader#18]
同人 漫画 cg cos 这些

**Comment by dipoo** [comment]
上周网站改版后，搜索参数也有变化，分类过滤都不能用了

**Comment by moyuxia** [comment]
这样啊，那还有机会整好吗，麻烦的话就算了 辛苦大佬了

**Comment by dipoo** [comment]
https://github.com/dipoo/egdownloader/raw/master/ext/egdownloader.jar
下载替换jre/lib/ext/下的文件就行

**Comment by moyuxia** [comment]
谢大佬
