### ISSUE TITLE
null字尾求解決

### ISSUE THREAD

**Issue by laijeffrey512** [dipoo/egdownloader#2]
下載不了 null字尾..ex更新了嗎?還是我個人問題.. 求解:"(

**Comment by dipoo** [comment]
我本机可以，ex应该没更新；

你把弹出错误的地方截个图出来，或者在根目录下看看有没有error.log的文件，把内容贴上来。

**Comment by laijeffrey512** [comment]
![default](https://cloud.githubusercontent.com/assets/6257103/7242237/a41f3672-e78e-11e4-87bb-1eee83c7b861.png)

**Comment by dipoo** [comment]
出现509图片，应该是配额不足了。
