### ISSUE TITLE
可以更新一个32位版本吗？

### ISSUE THREAD

**Issue by zyf722** [dipoo/egdownloader#23]
家里的电脑用的是64位的版本，软件本身很良心，但是希望作者额外发布一个32位版本以供随身携带。

**Comment by dipoo** [comment]
手上没有32系统，没办法校验。

**Comment by dipoo** [comment]
试着弄了个32位的，在64位系统能跑。先给你测试下，有问题反馈，没问题也请告知下。
https://pan.baidu.com/s/1Mr7riX12LqjRw4cFxPWLxg 提取码: neq5

**Comment by zyf722** [comment]
虚拟机测试可用。
抱歉最近一直没上github。经历了里站倒闭又恢复的风波，还是能完美支持，点赞！
