### ISSUE TITLE
里站挂了，大佬什么时候开发个适合表站的版本啊

### ISSUE THREAD

**Issue by hellokitty0316** [dipoo/egdownloader#26]
RT

**Comment by dipoo** [comment]
挂了？...

**Comment by hellokitty0316** [comment]
> 挂了？...

是的，挂了。事情应该是：荷兰通过了禁止儿童色情的法律，里站服务器在荷兰，今天站长发了公告说了这个事情

**Comment by hellokitty0316** [comment]
> 挂了？...

另外表站大概还会开放半年，然后也要关闭。

**Comment by dipoo** [comment]
先观望观望吧，表站也只能存活半年，还有什么搞头。

**Comment by hellokitty0316** [comment]
这就难受了，除表里站好像没有其它中文漫画资源充沛的在线漫画网站了。

**Comment by dipoo** [comment]
是啊，难受，看有没有人接手了。

**Comment by shiyinayuriko** [comment]
如果表站和里站数据结构一致的话，大概能马上出个版本

**Comment by hellokitty0316** [comment]
> 如果表站和里站数据结构一致的话，大概能马上出个版本

那我就拭目以待了😄

**Comment by dipoo** [comment]
表站something went wrong了

**Comment by hellokitty0316** [comment]
> 表站something went wrong了

我这里能正常登录

**Comment by dipoo** [comment]
发版本啦，适配表站，又可以耍半年了...

**Comment by hellokitty0316** [comment]
> 发版本啦，适配表站，又可以耍半年了...
大佬好快，我来试试~

**Comment by hellokitty0316** [comment]
> 发版本啦，适配表站，又可以耍半年了...

我更新完，重启后搜索失败；在设置内设置了代理，挂了梯子，还是搜索失败，请问如何解决？

**Comment by dipoo** [comment]
重试几次，我发现表站不太稳定。

**Comment by hellokitty0316** [comment]
好的

**Comment by hellokitty0316** [comment]
至今还是搜索失败：unexpected end of file from server
挂了梯子配置了代理，测试能成功找到ip，应该不是代理的问题。

**Comment by dipoo** [comment]
挂了梯子就不要配置代理了，这个错误可能是代理的问题。

**Comment by hellokitty0316** [comment]
不配置代理，发生的错误是：connect timed out

**Comment by dipoo** [comment]
unexpected end of file from server错误的报错发一下，在error.log里

**Comment by hellokitty0316** [comment]
java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:776)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:773)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1324)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.arong.egdownloader.spider.WebClient.getRequestUseJavaWithCookie(WebClient.java:493)
	at org.arong.egdownloader.ui.work.SearchComicWorker.doInBackground(SearchComicWorker.java:38)
	at org.arong.egdownloader.ui.work.SearchComicWorker.doInBackground(SearchComicWorker.java:1)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Jul 27, 2019 9:12:15 AM com.mchange.v2.log.MLog <clinit>
信息: MLog clients using java 1.4+ standard logging.
Jul 27, 2019 9:12:15 AM com.mchange.v2.c3p0.C3P0Registry banner
信息: Initializing c3p0-0.9.0.2 [built 26-September-2005 12:55:26 -0400; debug? true; trace: 10]
Jul 27, 2019 9:12:15 AM com.mchange.v2.c3p0.PoolBackedDataSource getPoolManager
信息: Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource@3a296a42[ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, description -> null, driverClass -> org.sqlite.JDBC, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, identityToken -> 3a296a42, idleConnectionTestPeriod -> -1, initialPoolSize -> 3, jdbcUrl -> jdbc:sqlite:data/data.db, loginTimeout -> 0, maxIdleTime -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, properties -> {user=******, password=******}, propertyCycle -> 300, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, usesTraditionalReflectiveProxies -> false ]

**Comment by dipoo** [comment]
浏览器设置这个代理访问表站没问题吗

**Comment by hellokitty0316** [comment]
梯子开了全局：
浏览器可以直接上表站，不用做设置；
idm下载需要做额外代理设置，服务器是127.0.0.1，端口1080；我在egdownload上做了和idm一样的代理设置

**Comment by dipoo** [comment]
手动创建一个任务，用http和https分别试下，看看效果

**Comment by hellokitty0316** [comment]
软件内没配置代理，手动新建连接失败；再配置代理后，搜索可以用了，手动新建任务也能成功；目前看来需要配置代理使用，连接可能不稳定。

**Comment by dipoo** [comment]
我用VPN还算稳定，但速度巨慢。

**Comment by hellokitty0316** [comment]
😕我用的公共线路，下载配额都被别人用完了（哭

**Comment by fortunelee** [comment]
啥时候能出个新版本呢

**Comment by dipoo** [comment]
@fortunelee 兄弟，出什么新版本？

**Comment by fortunelee** [comment]
@dipoo 那现在只能用梯子去玩了？？？？

**Comment by dipoo** [comment]
@fortunelee 是啊，表站只能这么玩
