### ISSUE TITLE
里站复活后创建任务出现Connection refused

### ISSUE THREAD

**Issue by Link-KS** [dipoo/egdownloader#28]
首先恭喜里站复活~历经七天的死亡，犹如耶稣死后复生一般再现神迹！
但是现在下载不了里站资源。我的版本是v0.95.7，尝试下载任何本子的时候都会出现Connection refuse的错误，如下图
![exh](https://user-images.githubusercontent.com/7877965/62371538-b1c13900-b567-11e9-9a0c-4f8264fa8a2a.png)

另附我尝试下载但失败的本子链接如下：
> https://exhentai.org/g/1455057/26d768f76b/
> https://exhentai.org/g/1438678/06a40c1195/
> https://exhentai.org/g/1453382/c75036ea93/

日志如下：
> 2019-08-02 20:56:11 正在检测版本...
> 2019-08-02 20:56:11 https://raw.githubusercontent.com/dipoo/egdownloader/master/script/egversion,proxy:null
> 2019-08-02 20:56:13 {"version":"0.95","url":"https://pan.baidu.com/s/1Za_diYdowWLzZmybEcSkjA","baidu_pan_code":"jww2","jarVersion":"9","date":"2019-08-01","jarUrl":"https://raw.githubusercontent.com/dipoo/egdownloader/master/ext/egdownloader.jar","changelog":"修复是否已创建、搜索脚本bug;使用之前请设置代理。"}
> 2019-08-02 20:56:26 https://exhentai.org/g/1455057/26d768f76b,proxy:null
> 2019-08-02 20:56:28 ScriptParser-2019-07-30 14:37
> 2019-08-02 20:56:28 ScriptParser-(COMIC1☆15) [milkberry, Tamakakeya (Kisaragi Miyu, Tamakake)] JC Saimin Mesuinu-ka Keikaku [Chinese] [绅士仓库Lolipoi联合汉化]
> 2019-08-02 20:56:28 ScriptParser-(COMIC1☆15) [milkberry、たまかけ屋 (如月みゆ、たまかけ)] JC催眠メス犬化計画 [中国翻訳]
> 2019-08-02 20:56:28 ScriptParser-BlossomPlus
> 2019-08-02 20:56:28 ScriptParser-Doujinshi
> 2019-08-02 20:56:28 ScriptParser-Chinese
> 2019-08-02 20:56:28 ScriptParser-23
> 2019-08-02 20:56:28 ScriptParser-54.59 M
> 2019-08-02 20:56:28 ScriptParser-http://exhentai.org/t/7c/d8/7cd86d1ea59261354b00d6220d416df18cf42c61-2425125-2081-3024-jpg_250.jpg
> 2019-08-02 20:56:28 http://exhentai.org/t/7c/d8/7cd86d1ea59261354b00d6220d416df18cf42c61-2425125-2081-3024-jpg_250.jpg,proxy:null

**Comment by dipoo** [comment]
同喜！
升级最新版本即可。

**Comment by Link-KS** [comment]
问题解决~感谢大大
