### ISSUE TITLE
未下载完的文件显示为“已完成”，并且无法继续下载

### ISSUE THREAD

**Issue by Link-KS** [dipoo/egdownloader#29]
我在下载一个110页的单行本的时候，下载器只下载了99页就停止下载，并显示“已完成”了。我尝试过对任务右键点击“开始任务”，也尝试过右键点击“更多操作 - 查缺补漏”，都未能继续下载任务。请问除了删掉重下之外还能怎么解决嘛？
![exh错误](https://user-images.githubusercontent.com/7877965/62412273-83f4f680-b632-11e9-8042-eb98911a7dad.png)

下面是本子链接：
https://exhentai.org/g/1456384/0e4441bd61/?p=2

下面是日志，太长了这里仅保留开头和结尾。下完第99张图后又开始了前面下载失败的图，下完又提示完成：
> 2019-08-03 09:49:34 DownloadWorker-[響樹はじめ] 少女ポルノ(1-110):开始下载
> 2019-08-03 09:49:34 https://exhentai.org/s/203799e66b/1456384-1,proxy:null
> 2019-08-03 09:49:35 http://221.223.63.26:30000/h/11f5003a28ffeea2654134a27e2a68e260e95a90-319083-1280-1807-jpg/keystamp=1564797300-a26966153e;fileindex=71704092;xres=1280/001.jpg,proxy:null
> 2019-08-03 09:49:36 DownloadWorker-[響樹はじめ] 少女ポルノ：001.jpg(311.60KB, 1280x1807)：下载完成，耗时0.92秒
> 2019-08-03 09:49:37 https://exhentai.org/s/bf60710b76/1456384-2,proxy:null
> 2019-08-03 09:49:38 http://223.17.201.176:19795/h/d630f50dc8d1206c8fdf6593d4853b80eb5714a1-58099-1280-1807-jpg/keystamp=1564797300-cc3d699ae1;fileindex=71704094;xres=1280/002.jpg,proxy:null
> （中略）
> 2019-08-03 10:05:02 https://exhentai.org/s/de16422615/1456384-99,proxy:null
> 2019-08-03 10:05:04 http://114.221.193.131:2315/h/5311752f728098df15d28db74ab36448fdba5f41-361961-1080-1704-jpg/keystamp=1564798500-eea8437427;fileindex=71704203;xres=2400/099.jpg,proxy:null
> 2019-08-03 10:05:04 DownloadWorker-[響樹はじめ] 少女ポルノ：099.jpg(353.48KB, 1080x1704)：下载完成，耗时0.59秒
> 2019-08-03 10:05:04 DownloadWorker-[響樹はじめ] 少女ポルノ(1-110):开始下载
> 2019-08-03 10:05:04 https://exhentai.org/s/3365ef3eaf/1456384-28,proxy:null
> 2019-08-03 10:05:06 http://114.34.196.84:8787/h/9f684eebba9c0d999e58aec6da94c376c39c8fe1-564320-1280-1807-jpg/keystamp=1564798500-aeb2721750;fileindex=71704132;xres=1280/028.jpg,proxy:null
> 2019-08-03 10:05:26 [響樹はじめ] 少女ポルノ：028.jpg-读取流超时，滞后重试，耗时20.00秒
> 2019-08-03 10:05:26 https://exhentai.org/s/5f9b583fd8/1456384-39,proxy:null
> 2019-08-03 10:05:27 http://103.97.33.190:54132/h/5bc98173b00467684d953580c1737b93fe78dcb6-634052-1280-1807-jpg/keystamp=1564798500-ff0b08f8e7;fileindex=71704143;xres=1280/039.jpg,proxy:null
> 2019-08-03 10:05:52 [響樹はじめ] 少女ポルノ：039.jpg-读取流超时，滞后重试，耗时25.38秒
> 2019-08-03 10:05:52 https://exhentai.org/s/bee2302ac1/1456384-50,proxy:null
> 2019-08-03 10:05:53 http://173.208.246.210:1028/h/e75a4a639aa2ee16fd955e84ab5efadb9d10da84-466870-1280-1807-jpg/keystamp=1564798500-c6c0594afa;fileindex=71704154;xres=1280/050.jpg,proxy:null
> 2019-08-03 10:06:01 DownloadWorker-[響樹はじめ] 少女ポルノ：050.jpg(455.93KB, 1280x1807)：下载完成，耗时7.85秒
> 2019-08-03 10:06:01 https://exhentai.org/s/8f07577f4c/1456384-70,proxy:null
> 2019-08-03 10:06:03 http://182.155.229.193:9696/h/af9205dcd23cb92ce24a9013b758ea8dfc122f37-559939-1280-1807-jpg/keystamp=1564798500-3c60cff86d;fileindex=71704174;xres=1280/070.jpg,proxy:null
> 2019-08-03 10:07:07 DownloadWorker-[響樹はじめ] 少女ポルノ：070.jpg(546.82KB, 1280x1807)：下载完成，耗时64.48秒
> 2019-08-03 10:07:07 https://exhentai.org/s/b12ee00d04/1456384-77,proxy:null
> 2019-08-03 10:07:10 http://182.155.229.193:9696/h/6e05254874bf3d997d0f4449810a088457ba4a09-651666-1280-1807-jpg/keystamp=1564798500-992b95cf7d;fileindex=71704181;xres=1280/077.jpg,proxy:null
> 2019-08-03 10:07:36 DownloadWorker-[響樹はじめ] 少女ポルノ：077.jpg(636.39KB, 1280x1807)：下载完成，耗时26.08秒
> 2019-08-03 10:07:36 https://exhentai.org/s/6f97d3c6ae/1456384-93,proxy:null
> 2019-08-03 10:07:37 http://183.51.225.30:36670/h/7ccfdf6f8cf2ded34a29a91ce7fda334cb1f2f7a-337995-1080-1705-jpg/keystamp=1564798500-2a58a0e7cf;fileindex=71704197;xres=2400/093.jpg,proxy:null
> 2019-08-03 10:08:39 [響樹はじめ] 少女ポルノ：093.jpg-读取流超时，滞后重试，耗时61.74秒
> 2019-08-03 10:08:39 DownloadWorker-[響樹はじめ] 少女ポルノ(1-110):开始下载
> 2019-08-03 10:08:39 https://exhentai.org/s/3365ef3eaf/1456384-28,proxy:null
> 2019-08-03 10:08:40 http://60.213.15.220:36755/h/9f684eebba9c0d999e58aec6da94c376c39c8fe1-564320-1280-1807-jpg/keystamp=1564798500-1fa58d3a29;fileindex=71704132;xres=1280/028.jpg,proxy:null
> 2019-08-03 10:08:41 DownloadWorker-[響樹はじめ] 少女ポルノ：028.jpg(551.09KB, 1280x1807)：下载完成，耗时1.09秒
> 2019-08-03 10:08:41 https://exhentai.org/s/5f9b583fd8/1456384-39,proxy:null
> 2019-08-03 10:08:43 http://111.241.158.231:14970/h/5bc98173b00467684d953580c1737b93fe78dcb6-634052-1280-1807-jpg/keystamp=1564798500-f6fe8ddebf;fileindex=71704143;xres=1280/039.jpg,proxy:null
> 2019-08-03 10:08:45 DownloadWorker-[響樹はじめ] 少女ポルノ：039.jpg(619.19KB, 1280x1807)：下载完成，耗时2.22秒
> 2019-08-03 10:08:45 https://exhentai.org/s/6f97d3c6ae/1456384-93,proxy:null
> 2019-08-03 10:08:46 http://110.164.169.250:1024/h/7ccfdf6f8cf2ded34a29a91ce7fda334cb1f2f7a-337995-1080-1705-jpg/keystamp=1564798500-3cab331edc;fileindex=71704197;xres=2400/093.jpg,proxy:null
> 2019-08-03 10:09:26 [響樹はじめ] 少女ポルノ：093.jpg-读取流超时，滞后重试，耗时39.92秒
> 2019-08-03 10:09:26 DownloadWorker-[響樹はじめ] 少女ポルノ(1-110):开始下载
> 2019-08-03 10:09:26 https://exhentai.org/s/6f97d3c6ae/1456384-93,proxy:null
> 2019-08-03 10:09:27 http://183.51.225.30:36670/h/7ccfdf6f8cf2ded34a29a91ce7fda334cb1f2f7a-337995-1080-1705-jpg/keystamp=1564798500-2a58a0e7cf;fileindex=71704197;xres=2400/093.jpg,proxy:null
> 2019-08-03 10:09:56 DownloadWorker-[響樹はじめ] 少女ポルノ：093.jpg(330.07KB, 1080x1705)：下载完成，耗时29.08秒
> 2019-08-03 10:09:57 DownloadWorker-==【[響樹はじめ] 少女ポルノ】已下载完毕==

**Comment by dipoo** [comment]
点开图片列表，哪些你认为没完成的就重置状态，然后再开始任务下载；或者可以单独选择图片下载。

**Comment by Link-KS** [comment]
然而图片列表里面只有99张图……
![exh错误2](https://user-images.githubusercontent.com/7877965/62414458-2f5f7480-b64e-11e9-9cbf-8089b1a27957.png)

**Comment by dipoo** [comment]
我重现不了你的问题，但我看你提供的地址后带了参数p=2，这是错误的，会造成采集的全部都是第三页的图片。

**Comment by Link-KS** [comment]
我删除掉任务再重新创建这个任务时，图片列表就恢复正常了，也是没法重现。不知道是不是之前在创建任务的时候出了问题。看创建任务时的日志是下面这样的。之后我忘了因为什么原因重启了一下，不知道是不是这个操作影响到图片列表

> 2019-08-03 09:44:35 https://exhentai.org/g/1456384/0e4441bd61,proxy:null
> 2019-08-03 09:44:36 ScriptParser-2019-08-02 14:14
> 2019-08-03 09:44:36 ScriptParser-[Hibiki Hajime] Shoujo Porno
> 2019-08-03 09:44:36 ScriptParser-[響樹はじめ] 少女ポルノ
> 2019-08-03 09:44:36 ScriptParser-alfredmeow
> 2019-08-03 09:44:36 ScriptParser-Manga
> 2019-08-03 09:44:36 ScriptParser-Japanese
> 2019-08-03 09:44:36 ScriptParser-110
> 2019-08-03 09:44:36 ScriptParser-240.7 M
> 2019-08-03 09:44:36 ScriptParser-https://exhentai.org/t/20/37/203799e66b8af5e57b76d90b3d2f290f6f55c805-2434569-2040-2880-jpg_250.jpg
> 2019-08-03 09:44:36 https://exhentai.org/g/1456384/0e4441bd61?p=1,proxy:null
> 2019-08-03 09:44:37 https://exhentai.org/g/1456384/0e4441bd61?p=2,proxy:null
> 2019-08-03 09:44:38 https://exhentai.org/t/20/37/203799e66b8af5e57b76d90b3d2f290f6f55c805-2434569-2040-2880-jpg_250.jpg,proxy:null
> 2019-08-03 09:44:50 TaskSqliteDbTemplate-database is locked, trying query tasks...
> 2019-08-03 09:44:51 TaskSqliteDbTemplate-database is locked, trying query tasks...
> 2019-08-03 09:45:00 TaskSqliteDbTemplate-database is locked, trying query tasks...
> 2019-08-03 09:45:06 TaskSqliteDbTemplate-database is locked, trying query tasks...
> 2019-08-03 09:45:18 正在检测版本...
> 2019-08-03 09:45:18 https://raw.githubusercontent.com/dipoo/egdownloader/master/script/egversion,proxy:null
> 2019-08-03 09:45:20 {"version":"0.95","url":"https://pan.baidu.com/s/1Za_diYdowWLzZmybEcSkjA","baidu_pan_code":"jww2","jarVersion":"11","date":"2019-08-02","jarUrl":"https://raw.githubusercontent.com/dipoo/egdownloader/master/ext/egdownloader.jar","changelog":"里站复活了；现在里表站兼容；修复搜索封面缓存问题。"}
> 2019-08-03 09:45:20 当前已是最新版本

**Comment by dipoo** [comment]
图片保存完毕之前关闭了软件引起的。

**Comment by Link-KS** [comment]
明白啦~以后我会注意的
