### ISSUE TITLE
配置里面设置代理部分，不能设置为系统代理吗？

### ISSUE THREAD

**Issue by mchotdograp** [dipoo/egdownloader#31]
这样用ssr之类的egdownloader里面就不用再设置什么了

**Comment by dipoo** [comment]
系统代理是什么原理，是指下载器自动读取系统的代理配置？之前有做过IE代理，不清楚是否是这回事，但由于需要新增一些库，所以没有开放。

**Comment by mchotdograp** [comment]
对的对的，就是跟着系统走，SSR设置好了后，不论是走全局代理还是走PAC，系统和所有应用都是统一的，这样不用每个应用分别设置了，很方便，真心希望可以这样啊，而且目前咱们这个软件的代理设置，对于很多使用SSR的人来说，有点摸不着头脑，不知道如何设置。
SSR代理一般长这样：[https://www.i5seo.com/wp-content/uploads/2017/10/2018013013375061.png](url)

**Comment by mchotdograp** [comment]
我试了几个，几乎都是红字提示说读取流超时，滞后重试。。。
这是什么情况呀？

**Comment by dipoo** [comment]
代理的问题吧。
试下配置socks， 服务器127.0.0.1，端口1080？

**Comment by mchotdograp** [comment]
试过了不行啊
而且账户名和密码输什么？ssr没什么账户名啊

**Comment by mchotdograp** [comment]
🆗了竟然 谢谢你！
