### ISSUE TITLE
里站模式搜索失败：JSON首字符不为 '['

### ISSUE THREAD

**Issue by zyf722** [dipoo/egdownloader#42]
切换表站可以正常访问，cookie尝试过还原但未能解决。

**Comment by dipoo** [comment]
里站搜索分页改版导致，我觉得这个改动体验不好，先观察一段时间吧，等这个改动稳定了，我找时间跟进下。

**Comment by dipoo** [comment]
里站搜索分页改版导致，我觉得这个改动体验不好，先观察一段时间吧，等这个改动稳定了，我找时间跟进下。

**Comment by zyf722** [comment]
> 里站搜索分页改版导致，我觉得这个改动体验不好，先观察一段时间吧，等这个改动稳定了，我找时间跟进下。

好的，感谢。

**Comment by dipoo** [comment]
已更新，升级最新版本及脚本即可
