### ISSUE TITLE
创建异常:Received fatal alert: handshake_ failure

### ISSUE THREAD

**Issue by user11451411919810** [dipoo/egdownloader#44]
已经更新JAR和脚本，表站没有问题但是里站会报Received fatal alert: handshake_ failure，host也试过修改还是不行
走代理下载的，连接测试结果正常
版本检查更新提示已经是目前最新版本，脚本配置那里同步脚本提示远程脚本未更新或更新不可用

**Comment by dipoo** [comment]
截一个控制台的图，看看封面地址是什么

**Comment by user11451411919810** [comment]
本子封面图缓存吗？
![QQ截图20230525064838](https://github.com/dipoo/egdownloader/assets/134526936/5634d36e-c4ac-4935-9051-22bdaaae4730)

**Comment by dipoo** [comment]
不是这里，是创建任务时下面控制台的输出信息

**Comment by user11451411919810** [comment]
![QQ图片20230525193419](https://github.com/dipoo/egdownloader/assets/134526936/1716e004-def2-45cf-96ca-74c84fc242d2)
不好意思现在才回复，如图所示

**Comment by user11451411919810** [comment]
换成用socks代理的话则直接变成这样的报错
![QQ截图20230525195521](https://github.com/dipoo/egdownloader/assets/134526936/a95095f7-0ea1-4250-9d6c-7edc36d51c50)
但是脚本那里提示是远程脚本未更新或更新不可用

**Comment by dipoo** [comment]
不是说让你换成socks。
你的代理（VPN）是单节点的吗？
不行你就不走代理走hosts吧，178.175.129.254 www.exhentai.org

**Comment by dipoo** [comment]
有时候与网络有关，各方面
