### ISSUE TITLE
本程序不允许多开 error

### ISSUE THREAD

**Issue by charnameLipo** [dipoo/egdownloader#5]
开启程序时显示“本程序不允许多开”，重启后依旧无法打开。

**Comment by dipoo** [comment]
出现这种情况的时候要杀进程
打开任务管理器，找到egdownloader.exe或者javaw.exe杀掉

**Comment by bear-shen** [comment]
嗯……我翻了一下代码…………50000号端口和有道词典【_(TωT」∠)_没错就是有道词典】冲突了………………导致了不允许多开问题…………

**Comment by dipoo** [comment]
...谢谢反馈...看来得换个端口号了...

**Comment by charnameLipo** [comment]
谢谢回答，有道词典跟好多程序都冲突……
